import { useMemo, useState, type ReactNode } from "react";
import { Activity, Award, CalendarDays, ChevronLeft, ChevronRight, ExternalLink, FileImage, GitCommit, Minus, Plus, RefreshCw, Trash2, Trophy, WifiOff } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { useMode } from "../../app/ModeContext";
import { Avatar } from "../../shared/components/Avatar";
import { Badge, Button, Card, EmptyState, SectionTitle, Skeleton } from "../../shared/components/ui";
import { PageHeader } from "../../shared/components/PageHeader";
import { desktopApi } from "../../shared/lib/tauri";
import { APP_TIME_ZONE, dateTime, fullNumber, percent, rulesetLabels } from "../../shared/lib/format";
import type { CareerCalendarDay, CareerDayDetail, CareerStats, Score } from "../../shared/types/osu";
import { careerCalendarKey, useCareerCalendar, useCareerDay, useCareerStatus, useOwnProfile } from "./api";
import { interpolateStats, monthDays, monthRange, weekday } from "./careerModel";

const statLabels: Array<[keyof CareerStats, string, (value: number | null) => string]> = [
  ["pp", "PP", (value) => value == null ? "—" : value.toFixed(2)],
  ["global_rank", "全球排名", (value) => value == null ? "—" : `#${fullNumber(Math.round(value))}`],
  ["country_rank", "地区排名", (value) => value == null ? "—" : `#${fullNumber(Math.round(value))}`],
  ["ranked_score", "排名分", fullNumber], ["total_score", "总分", fullNumber],
  ["hit_accuracy", "准确率", percent], ["play_count", "游戏次数", fullNumber],
  ["play_time", "游戏时长", (value) => value == null ? "—" : `${(value / 3600).toFixed(1)} 小时`],
  ["total_hits", "总命中数", fullNumber], ["maximum_combo", "最大连击", (value) => value == null ? "—" : `${fullNumber(value)}x`],
];

type DiffFilter = "all" | "added" | "removed" | "changed";
type QueueItem = { icon: ReactNode; tone: string; title: string; detail: string; action?: ReactNode };

function shiftMonth(year: number, month: number, amount: number) { const next = new Date(Date.UTC(year, month + amount, 1)); return { year: next.getUTCFullYear(), month: next.getUTCMonth() }; }
function scoreTitle(score: Score) { return score.beatmapset?.title ?? score.beatmap?.version ?? `成绩 #${score.id ?? "—"}`; }
function scoreUrl(score: Score) { return score.beatmap?.id ? `https://osu.ppy.sh/beatmaps/${score.beatmap.id}` : null; }
function signed(value: number | null, digits = 0) { return value == null || !Number.isFinite(value) ? "—" : `${value > 0 ? "+" : ""}${value.toFixed(digits)}`; }
function fillMonthDays(year: number, month: number, source: CareerCalendarDay[]) { const byDate = new Map(source.map((day) => [day.date, day])); return monthDays(year, month).map((date) => byDate.get(date) ?? { date, status: "missing", captured_at: null, stats: null, error: null, has_diff: false, added_scores: 0, removed_scores: 0, changed_scores: 0, added_medals: 0, added_replays: 0, added_screenshots: 0 }); }

function buildQueue(detail: CareerDayDetail | undefined, current: CareerStats | null, previous: CareerStats | null): QueueItem[] {
  if (!detail) return [];
  const events: QueueItem[] = [];
  if (current && previous) {
    const pp = current.pp != null && previous.pp != null ? current.pp - previous.pp : null;
    if (pp != null && Math.abs(pp) >= 0.01) events.push({ icon: <Activity className="size-4" />, tone: "text-pink-200", title: `PP ${pp > 0 ? "上升" : "下降"} ${Math.abs(pp).toFixed(2)}`, detail: `${previous.pp!.toFixed(2)} → ${current.pp!.toFixed(2)} PP` });
    const rank = current.global_rank != null && previous.global_rank != null ? current.global_rank - previous.global_rank : null;
    if (rank != null && Math.abs(rank) >= 1) events.push({ icon: <Trophy className="size-4" />, tone: rank < 0 ? "text-emerald-200" : "text-amber-200", title: rank < 0 ? `全球排名提升 ${Math.abs(Math.round(rank))} 位` : `全球排名变化 ${Math.abs(Math.round(rank))} 位`, detail: `#${Math.round(previous.global_rank!)} → #${Math.round(current.global_rank!)}` });
    const accuracy = current.hit_accuracy != null && previous.hit_accuracy != null ? current.hit_accuracy - previous.hit_accuracy : null;
    if (accuracy != null && Math.abs(accuracy) >= 0.001) events.push({ icon: <Activity className="size-4" />, tone: "text-cyan-200", title: `准确率 ${accuracy > 0 ? "提升" : "变化"} ${Math.abs(accuracy).toFixed(2)}%`, detail: `${previous.hit_accuracy!.toFixed(2)}% → ${current.hit_accuracy!.toFixed(2)}%` });
  }
  for (const item of detail.score_diffs) {
    const position = item.kind === "removed" ? `#${item.before_position}` : `#${item.after_position}`;
    events.push({ icon: item.kind === "added" ? <Plus className="size-4" /> : item.kind === "removed" ? <Minus className="size-4" /> : <RefreshCw className="size-4" />, tone: item.kind === "added" ? "text-emerald-200" : item.kind === "removed" ? "text-rose-200" : "text-amber-200", title: `BP ${item.kind === "added" ? "插入" : item.kind === "removed" ? "掉出" : "发生变化"} ${position}`, detail: `${scoreTitle(item.score)} · ${item.score.pp?.toFixed(2) ?? "—"}pp`, action: scoreUrl(item.score) ? <button aria-label="打开官方谱面" className="text-slate-500 hover:text-white" onClick={() => void desktopApi.openExternal(scoreUrl(item.score)!)} type="button"><ExternalLink className="size-4" /></button> : undefined });
  }
  for (const item of detail.medal_events) events.push({ icon: <Award className="size-4" />, tone: "text-amber-200", title: "获得新奖章", detail: `奖章 #${item.name}` });
  for (const item of detail.media_events) events.push({ icon: item.payload?.kind === "replay" ? <GitCommit className="size-4" /> : <FileImage className="size-4" />, tone: "text-violet-200", title: item.payload?.kind === "replay" ? "新增回放" : "新增截图", detail: `${item.name} · ${item.client ?? "本地"}` });
  return events;
}

export function CareerPage() {
  const { ruleset } = useMode();
  const profileQuery = useOwnProfile(ruleset); const statusQuery = useCareerStatus(); const queryClient = useQueryClient();
  const nowParts = new Intl.DateTimeFormat("en-US", { timeZone: APP_TIME_ZONE, year: "numeric", month: "numeric" }).formatToParts(new Date());
  const [month, setMonth] = useState({ year: Number(nowParts.find((part) => part.type === "year")?.value ?? new Date().getFullYear()), month: Number(nowParts.find((part) => part.type === "month")?.value ?? new Date().getMonth() + 1) - 1 });
  const range = monthRange(month.year, month.month); const calendarQuery = useCareerCalendar(ruleset, range.start, range.end);
  const days = useMemo(() => interpolateStats(fillMonthDays(month.year, month.month, calendarQuery.data?.days ?? [])), [calendarQuery.data?.days, month.month, month.year]);
  const [selectedDate, setSelectedDate] = useState<string | null>(null); const [diffFilter, setDiffFilter] = useState<DiffFilter>("all"); const [capturing, setCapturing] = useState(false);
  const selected = selectedDate && days.some((day) => day.date === selectedDate) ? selectedDate : [...days].reverse().find((day) => day.status === "captured")?.date ?? null;
  const dayQuery = useCareerDay(ruleset, selected); const calendarSelected = selected ? days.find((day) => day.date === selected) : undefined; const detail = dayQuery.data;
  const displayStats = detail?.stats ?? calendarSelected?.stats ?? null; const previous = detail?.previous_stats ?? (calendarSelected ? days.slice(0, days.indexOf(calendarSelected)).reverse().find((day) => day.status === "captured")?.stats ?? null : null); const queue = buildQueue(detail, displayStats, previous);
  const activityDays = [...days].filter((day) => day.status === "captured" && day.has_diff).reverse();
  const capture = async () => { setCapturing(true); try { await desktopApi.captureCareerSnapshot(ruleset, true); await Promise.all([statusQuery.refetch(), calendarQuery.refetch(), dayQuery.refetch()]); await queryClient.invalidateQueries({ queryKey: careerCalendarKey(ruleset, range.start, range.end) }); } finally { setCapturing(false); } };
  const clearHistory = async () => { if (!window.confirm("确定清空全部生涯历史吗？此操作不可恢复。")) return; await desktopApi.clearCareerHistory(); await queryClient.invalidateQueries({ queryKey: ["career-calendar", ruleset] }); await statusQuery.refetch(); };
  if (profileQuery.isLoading || statusQuery.isLoading) return <div className="space-y-5"><Skeleton className="h-24" /><Skeleton className="h-96" /></div>;
  const profile = profileQuery.data?.data;
  if (!profile) return <EmptyState icon={<Activity className="size-5" />} title="暂时无法读取生涯数据" description="请先登录 osu!，然后重试。" action={<Button onClick={() => void profileQuery.refetch()}>重试</Button>} />;
  const cells = [...Array.from({ length: weekday(range.start) }, () => null), ...days];
  return <div className="space-y-5">
    <PageHeader title="生涯动态" actions={<div className="flex gap-2"><Button onClick={() => void clearHistory()} size="sm" variant="ghost"><Trash2 className="size-4" />清空历史</Button><Button loading={capturing} onClick={() => void capture()} size="sm"><RefreshCw className="size-4" />立即采集</Button></div>} />
    <Card className="relative overflow-hidden p-6"><div className="absolute inset-0 bg-gradient-to-r from-pink-400/10 via-transparent to-cyan-300/10" /><div className="relative flex flex-wrap items-center gap-4"><Avatar profile={profile} className="size-14 rounded-2xl border-2 border-white/10" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-white">{profile.username}</h2><Badge tone="cyan">{rulesetLabels[ruleset]}</Badge>{statusQuery.data?.configured ? <Badge tone="success">历史记录已启用</Badge> : <Badge tone="warning">等待本地数据库</Badge>}</div><p className="mt-1 text-xs text-slate-400">把每天真正发生的变化排成一条动态流；没有 BP、奖章或媒体变化的日期不会制造空事件。</p></div><div className="text-right text-xs text-slate-500"><p>{statusQuery.data?.snapshot_count ?? 0} 条快照</p><p className="mt-1">{statusQuery.data?.latest_date ? `最近 ${statusQuery.data.latest_date}` : "尚未采集"}</p></div></div></Card>
    {!statusQuery.data?.configured ? <Card className="flex items-center gap-3 border-amber-300/15 bg-amber-300/[0.06] p-4 text-sm text-amber-100"><WifiOff className="size-4" />请先在“本地数据”中配置数据库，生涯动态才会保存。</Card> : null}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.3fr)_minmax(300px,.7fr)]">
      <Card className="p-5"><div className="flex items-start justify-between gap-4"><SectionTitle eyebrow="Activity queue" title={selected ? `${selected} 的动态` : "等待第一条动态"} description={calendarSelected?.status === "interpolated" ? "这是连续数值估算日期，事件保持空白。" : "按当天采集结果生成，事件缺失时保持安静。"} /><Activity className="size-5 text-pink-200" /></div><div className="mt-5">{queue.length ? <div className="space-y-1">{queue.map((item, index) => <div className="relative flex gap-3 py-3" key={`${item.title}-${index}`}><div className="relative z-10 grid size-8 shrink-0 place-items-center rounded-xl border border-white/[.08] bg-[var(--surface-panel)]"><span className={item.tone}>{item.icon}</span></div>{index < queue.length - 1 ? <span className="absolute bottom-0 left-4 top-11 w-px bg-white/[.08]" /> : null}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-sm font-semibold text-white">{item.title}</p>{item.action}</div><p className="mt-1 truncate text-xs text-slate-500">{item.detail}</p></div></div>)}</div> : <div className="rounded-2xl border border-dashed border-white/[.1] px-6 py-10 text-center"><Activity className="mx-auto size-7 text-slate-600" /><p className="mt-3 text-sm font-semibold text-slate-300">这一天没有事件</p><p className="mt-1 text-xs text-slate-600">连续数值仍可在下方查看，BP、奖章、回放与截图只在真实采集日出现。</p></div>}</div></Card>
      <Card className="p-5"><SectionTitle eyebrow="Queue index" title="有动态的日期" description="点击日期切换消息队列" /><div className="mt-4 space-y-1">{activityDays.length ? activityDays.slice(0, 12).map((day) => <button className={`flex w-full items-center justify-between rounded-xl px-3 py-2 text-left transition ${day.date === selected ? "bg-[var(--theme-primary)]/10 text-white" : "text-slate-400 hover:bg-white/[.04] hover:text-white"}`} key={day.date} onClick={() => setSelectedDate(day.date)} type="button"><span className="text-xs font-medium">{day.date}</span><span className="text-[10px] text-slate-600">{day.added_scores + day.removed_scores + day.changed_scores + day.added_medals + day.added_replays + day.added_screenshots} 条</span></button>) : <p className="py-8 text-center text-xs text-slate-600">暂无事件队列</p>}</div></Card>
    </div>
    <Card className="p-5"><div className="flex items-center justify-between"><SectionTitle eyebrow="Calendar" title={`${month.year} 年 ${month.month + 1} 月`} description="实线为快照，虚线为连续数值估算" /><div className="flex gap-1"><Button aria-label="上个月" onClick={() => setMonth((value) => shiftMonth(value.year, value.month, -1))} size="icon" variant="ghost"><ChevronLeft className="size-4" /></Button><Button aria-label="下个月" onClick={() => setMonth((value) => shiftMonth(value.year, value.month, 1))} size="icon" variant="ghost"><ChevronRight className="size-4" /></Button></div></div><div className="mt-5 grid grid-cols-7 gap-1 text-center text-[10px] text-slate-600">{["日", "一", "二", "三", "四", "五", "六"].map((label) => <span key={label}>{label}</span>)}{cells.map((day, index) => day ? <button aria-label={day.date} className={`min-h-16 rounded-xl border p-2 text-left transition ${day.date === selected ? "border-[var(--theme-primary)] bg-[var(--theme-primary)]/10" : "border-white/[.05] bg-white/[.02] hover:border-white/[.15]"} ${day.status === "interpolated" ? "border-dashed" : ""}`} key={day.date} onClick={() => setSelectedDate(day.date)} type="button"><span className="text-[10px] text-slate-500">{Number(day.date.slice(-2))}</span>{day.stats ? <><span className={`mt-2 block truncate font-mono text-[10px] ${day.status === "interpolated" ? "text-slate-400" : "text-cyan-100"}`}>{day.stats.pp?.toFixed(0)}pp</span><span className="mt-1 block text-[9px] text-slate-600">{day.has_diff ? `${day.added_scores + day.removed_scores + day.changed_scores} BP` : day.status === "interpolated" ? "估算" : ""}</span></> : day.status === "unavailable" ? <span className="mt-2 block text-[9px] text-amber-200">失败</span> : null}</button> : <span key={`empty-${index}`} />)}</div></Card>
    {displayStats ? <Card className="p-5"><div className="flex items-start justify-between"><SectionTitle eyebrow={calendarSelected?.status === "interpolated" ? "Estimated metrics" : "Snapshot metrics"} title={selected ?? "—"} description={detail?.captured_at ? `采集于 ${dateTime(detail.captured_at)}` : "断档期间的连续数值估算"} /><CalendarDays className="size-5 text-cyan-200" /></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{statLabels.map(([key, label, format]) => { const current = displayStats[key] ?? null; const before = previous?.[key] ?? null; const delta = current != null && before != null ? current - before : null; return <div className="rounded-xl border border-white/[.06] bg-white/[.025] p-3" key={key}><p className="text-[10px] text-slate-500">{label}</p><p className="mt-1 font-mono text-sm font-semibold text-white">{format(current)}</p><p className={`mt-1 text-[10px] ${delta != null && delta > 0 ? "text-emerald-200" : "text-slate-600"}`}>{delta == null ? "—" : signed(delta, key === "pp" || key === "hit_accuracy" ? 2 : 0)}</p></div>; })}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><TrendChart days={days} metric="pp" label="PP 趋势" /><TrendChart days={days} metric="global_rank" label="全球排名趋势" /></div></Card> : <EmptyState icon={<CalendarDays className="size-5" />} title={selected ? `${selected} 没有可用数值` : "选择一个日期"} description={detail?.error ?? "还没有足够的真实快照生成连续数值。"} />}
    {detail ? <Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><SectionTitle eyebrow="BP detail" title="Top 200 变化" description="事件队列显示摘要，这里保留完整筛选" /><div className="flex gap-1">{(["all", "added", "removed", "changed"] as DiffFilter[]).map((value) => <Button key={value} onClick={() => setDiffFilter(value)} size="sm" variant={diffFilter === value ? "primary" : "ghost"}>{value === "all" ? "全部" : value === "added" ? "新增" : value === "removed" ? "掉出" : "变化"}</Button>)}</div></div><div className="mt-3 grid gap-2 md:grid-cols-2">{detail.score_diffs.filter((item) => diffFilter === "all" || item.kind === diffFilter).map((item) => <div className="flex items-center gap-3 rounded-xl border border-white/[.06] bg-white/[.02] p-3" key={`${item.kind}-${item.key}`}><span className={`grid size-7 place-items-center rounded-lg ${item.kind === "added" ? "bg-emerald-300/10 text-emerald-200" : item.kind === "removed" ? "bg-rose-300/10 text-rose-200" : "bg-amber-300/10 text-amber-200"}`}>{item.kind === "added" ? <Plus className="size-3" /> : item.kind === "removed" ? <Minus className="size-3" /> : <RefreshCw className="size-3" />}</span><div className="min-w-0 flex-1"><p className="truncate text-xs text-white">{scoreTitle(item.score)}</p><p className="text-[10px] text-slate-500">{item.before_position ? `#${item.before_position} → ` : ""}{item.after_position ? `#${item.after_position}` : "掉出前 200"} · {item.score.pp?.toFixed(2) ?? "—"}pp</p></div>{scoreUrl(item.score) ? <button aria-label="打开官方谱面" className="text-slate-500 hover:text-white" onClick={() => void desktopApi.openExternal(scoreUrl(item.score)!)} type="button"><ExternalLink className="size-3.5" /></button> : null}</div>)}{!detail.score_diffs.length ? <p className="py-6 text-center text-xs text-slate-600">当天没有 BP 变化。</p> : null}</div></Card> : null}
  </div>;
}

function TrendChart({ days, metric, label }: { days: CareerCalendarDay[]; metric: keyof CareerStats; label: string }) { const values = days.map((day, index) => ({ day, index, value: day.stats?.[metric] })).filter((point): point is { day: CareerCalendarDay; index: number; value: number } => typeof point.value === "number"); if (values.length < 2) return null; const min = Math.min(...values.map((point) => point.value)); const max = Math.max(...values.map((point) => point.value)); const span = max - min || 1; const pointFor = (point: (typeof values)[number]) => `${(point.index / Math.max(days.length - 1, 1)) * 100},${54 - ((point.value - min) / span) * 44}`; return <div className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><p className="text-[10px] text-slate-500">{label} <span className="text-slate-700">· 虚线点为估算</span></p><svg aria-label={label} className="mt-2 h-14 w-full overflow-visible" preserveAspectRatio="none" viewBox="0 0 100 60"><polyline fill="none" points={values.map(pointFor).join(" ")} stroke="rgb(103 232 249)" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" />{values.map((point) => <circle cx={pointFor(point).split(",")[0]} cy={pointFor(point).split(",")[1]} fill={point.day.status === "interpolated" ? "rgb(15 23 42)" : "rgb(103 232 249)"} r="2" stroke="rgb(103 232 249)" strokeDasharray={point.day.status === "interpolated" ? "1 1" : undefined} strokeWidth="1" key={point.day.date} />)}</svg></div>; }
